# Please set 'QIITA_TOKEN' secret to your repository
name: Publish articles

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm run qiita:concat:declarative
      # https://github.com/increments/qiita-cli/blob/main/actions/publish/action.yml
      - uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
      - name: Install qiita-cli
        run: npm install -g @qiita/qiita-cli@v1.6.2
        shell: bash
      - name: Publish articles
        run: cd qiita && qiita publish --all
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        shell: bash
      - name: Commit and push diff
        run: |
          git add qiita/public/*
          if ! git diff --staged --exit-code --quiet; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -m "${COMMIT_MESSAGE}"
            git push
          fi
        shell: bash
        env:
          COMMIT_MESSAGE: Updated by qiita-cli
